### PR TITLE
Content item title and content item teaser heading

### PR DESCRIPTION
**Pull request by frederfred**
@martinlissmyr after having a look, I don't think it make sense to merge configuration for content item and content item teaser.

Specifying some kind of config inheritance could perhaps be the way to go, but I went for duplication for now. Hope that's fine.

### CODE REVIEW

**Comment by martinlissmyr** [comment]
Ok. But I would currently interpret this as there being two settings. One specifically for teasers and one specifically for content items. But maybe that is fine?

**Comment by frederfred** [comment]
@martinlissmyr you are right – I didn't think about that.

Made a stab at describing inherited configuration: https://github.com/Oktavilla/hopp-docs/pull/17/commits/5874f97eec69382ade4798cdc879b82657446957

WDYT?

**Comment by martinlissmyr** [comment]
There already is a way to describe inheritance  😄 

```
{% include fields-table.md parent_definition="content-item-fields" definition="content-type-article-fields" %}

\* Basic [Content Item field](content-item.md#fields)
```

**Comment by frederfred** [comment]
Ah, I see. But everything is not inherited. Only the two properties I defined.

**Comment by martinlissmyr** [comment]
> Ah, I see. But everything is not inherited.

I would argue that they are... They might not be relevant. But it makes sense that they are "inherited" because it's the same entity.

**Comment by frederfred** [comment]
Take two: ae1cb9299159e02d969788baecbcf7cb77a5c535

**Comment by martinlissmyr** [comment]
That will probably do it. 👍

--
Martin Lissmyr
Partner & Product/UX Designer
Oktavilla Design

**Pull request merged**
